// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iuneifvskwlnmilknupg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1bmVpZnZza3dsbm1pbGtudXBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTQ5NTgsImV4cCI6MjA3MTE5MDk1OH0.yJtmTNega-zoJ9ReONY17IdDxKbYmZt0YacoZKh80nk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});